# Generated by Django 4.0.4 on 2022-06-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('faq', '0002_faqfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqfeedback',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
    ]
