# Generated by Django 4.0.4 on 2022-06-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('faq', '0003_alter_faqfeedback_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='faq',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='faq',
            name='title_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='faq',
            name='title_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='faqfeedback',
            name='message_en',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='faqfeedback',
            name='message_ru',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='faqfeedback',
            name='title_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='faqfeedback',
            name='title_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Subject'),
        ),
    ]
