# Generated by Django 3.2.7 on 2022-05-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=155, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=155, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=155, null=True, verbose_name='Your Email')),
                ('phone', models.CharField(max_length=10, verbose_name='Your Phone')),
                ('title', models.CharField(max_length=155, verbose_name='Your Subject')),
                ('message', models.TextField(verbose_name='Your Message')),
                ('checked', models.BooleanField(default=False, verbose_name='Checked')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Форма обратной связь',
                'verbose_name_plural': 'Формы обратной связи',
            },
        ),
    ]
