# Generated by Django 3.2.7 on 2022-05-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание 1')),
                ('description2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание 2')),
            ],
            options={
                'verbose_name': 'Наш контакт',
                'verbose_name_plural': 'Наши контакты',
            },
        ),
    ]
