# Generated by Django 3.2.7 on 2022-05-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contact', '0002_ourcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
