# Generated by Django 3.2.7 on 2022-05-27 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contact', '0003_subscribe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'Подписка по email', 'verbose_name_plural': 'Подписки по email'},
        ),
    ]
