# Generated by Django 4.0.4 on 2022-06-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contact', '0005_delete_ourcontact_remove_feedback_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.IntegerField(verbose_name='Your Phone'),
        ),
    ]
