# Generated by Django 4.0.4 on 2022-06-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contact', '0006_alter_feedback_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='message_en',
            field=models.TextField(null=True, verbose_name='Your Message'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='message_ru',
            field=models.TextField(null=True, verbose_name='Your Message'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='title_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Your Subject'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='title_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Your Subject'),
        ),
    ]
