# Generated by Django 4.0.4 on 2022-06-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_of_post',
            new_name='posted',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='posts_text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='visits',
            new_name='visit_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_of_change',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default=None, upload_to='photos/posts/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
