# Generated by Django 4.0.4 on 2022-06-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_alter_post_options_rename_date_of_post_post_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='posts_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='posts_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
