# Generated by Django 4.0.4 on 2022-06-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='notes_ru',
            field=models.TextField(null=True),
        ),
    ]
