# Generated by Django 4.0.5 on 2022-06-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('checkout', '0002_order_notes_en_order_notes_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(default=False, max_length=5),
            preserve_default=False,
        ),
    ]
