# Generated by Django 4.0.4 on 2022-06-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0003_review_title_alter_product_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Продукция', 'verbose_name_plural': 'Продукция'},
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, upload_to='photos/products/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
