# Generated by Django 4.0.4 on 2022-06-16 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0005_product_content_en_product_content_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_ru',
        ),
    ]
